---

- name: create build workspace
  file:
    path: /tmp/{{docker_image}}
    state: directory
    mode: 0777

- name: construct Dockerfile
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - { src: "Dockerfile.j2",  dest: "/tmp/{{ docker_image }}/Dockerfile" }
    - { src: "{{ app }}.sh.j2", dest: "/tmp/{{ docker_image}}/{{ app }}.sh" }
    - { src: "{{ app }}_finish.sh.j2", dest: "/tmp/{{ docker_image}}/{{ app }}_finish.sh" }
     

- name: copy app
  copy:
    src: "{{ app }}.tar.gz"
    dest: "/tmp/{{ docker_image }}"

- name: docker build
  shell: "docker build --no-cache --rm=true -t {{ docker_registry }}/{{ docker_org }}/{{ docker_image }}:{{ docker_image_version }} ."
  args:
    chdir: "/tmp{{ docker_image }}"
  register: build_op

- name: docker tag as release
  shell: "docker tag {{ docker_registry }}/{{ docker_org }}/{{ docker_image }}:{{ docker_image_version }} {{ docker_registry }}/{{ docker_org }}/{{ docker_image }}:release"

- name: docker save
  shell: "docker save -o /tmp/{{docker_image}}/{{ docker_image }}_{{ docker_image_version }}.tar {{ docker_registry }}/{{ docker_org }}/{{ docker_image }}:release"